const fs = require('fs');
const { Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell, WidthType, ImageRun, AlignmentType, BorderStyle, ShadingType, PageBreak, TableOfContents, Footer, PageNumber, LevelFormat } = require('docx');
process.chdir(require('path').join(__dirname,'..'));
const T = JSON.parse(fs.readFileSync('data/derived/tables.json'));

const FONT = 'Calibri';
const p = (text, opts = {}) => new Paragraph({ spacing: { after: 120, line: 276 }, ...opts.para, children: (Array.isArray(text) ? text : [text]).map(t => typeof t === 'string' ? new TextRun({ text: t, font: FONT, size: 22, ...opts.run }) : t) });
const b = (t) => new TextRun({ text: t, bold: true, font: FONT, size: 22 });
const i = (t) => new TextRun({ text: t, italics: true, font: FONT, size: 22 });
const h1 = (t) => new Paragraph({ heading: HeadingLevel.HEADING_1, spacing: { before: 360, after: 160 }, children: [new TextRun({ text: t, font: FONT })] });
const h2 = (t) => new Paragraph({ heading: HeadingLevel.HEADING_2, spacing: { before: 280, after: 120 }, children: [new TextRun({ text: t, font: FONT })] });
const h3 = (t) => new Paragraph({ heading: HeadingLevel.HEADING_3, spacing: { before: 200, after: 80 }, children: [new TextRun({ text: t, font: FONT })] });
const bullet = (runs) => new Paragraph({ numbering: { reference: 'bul', level: 0 }, spacing: { after: 80 }, children: (Array.isArray(runs) ? runs : [runs]).map(t => typeof t === 'string' ? new TextRun({ text: t, font: FONT, size: 22 }) : t) });
const numbered = (runs) => new Paragraph({ numbering: { reference: 'num', level: 0 }, spacing: { after: 100 }, children: (Array.isArray(runs) ? runs : [runs]).map(t => typeof t === 'string' ? new TextRun({ text: t, font: FONT, size: 22 }) : t) });
const caption = (t) => new Paragraph({ spacing: { before: 60, after: 200 }, children: [new TextRun({ text: t, font: FONT, size: 18, italics: true, color: '52514E' })] });
const note = (t) => new Paragraph({ spacing: { before: 40, after: 240 }, children: [new TextRun({ text: t, font: FONT, size: 17, color: '52514E' })] });
const fig = (file, w, h) => new Paragraph({ alignment: AlignmentType.CENTER, spacing: { before: 120, after: 40 }, children: [new ImageRun({ type: 'png', data: fs.readFileSync('charts/'+file), transformation: { width: w, height: h } })] });

const TOTAL = 9360;
function table(rows, widths, opts = {}) {
  const sum = widths.reduce((a, c) => a + c, 0); const cw = widths.map(x => Math.round(x / sum * TOTAL));
  const bd = { style: BorderStyle.SINGLE, size: 4, color: 'D8D6CF' };
  return new Table({ width: { size: TOTAL, type: WidthType.DXA }, columnWidths: cw, rows: rows.map((r, ri) => new TableRow({ tableHeader: ri === 0, children: r.map((c, ci) => {
    const isHead = ri === 0; const isGroup = opts.groupRows && r.slice(1).every(x => x === '');
    return new TableCell({ width: { size: cw[ci], type: WidthType.DXA }, borders: { top: bd, bottom: bd, left: { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' }, right: { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' } },
      shading: isHead ? { type: ShadingType.CLEAR, fill: 'EEF3FA', color: 'auto' } : (isGroup ? { type: ShadingType.CLEAR, fill: 'F5F4F0', color: 'auto' } : undefined),
      margins: { top: 40, bottom: 40, left: 80, right: 80 },
      children: [new Paragraph({ alignment: ci === 0 ? AlignmentType.LEFT : AlignmentType.RIGHT, spacing: { after: 0 }, children: [new TextRun({ text: String(c), font: FONT, size: opts.size || 18, bold: isHead || isGroup })] })] });
  }) })) });
}

const children = [];
// ---------- Title
children.push(new Paragraph({ spacing: { before: 1200, after: 200 }, children: [new TextRun({ text: 'AI at Work in the United States', font: FONT, size: 52, bold: true })] }));
children.push(new Paragraph({ spacing: { after: 200 }, children: [new TextRun({ text: 'Evidence from the first public person-level dataset with an explicit AI-at-work module: the Census Bureau’s March 2026 Household Trends and Outlook Pulse Survey (HTOPS)', font: FONT, size: 28, color: '52514E' })] }));
children.push(new Paragraph({ spacing: { after: 100 }, children: [new TextRun({ text: 'Analytical report prepared for Workplace Social Science', font: FONT, size: 22 })] }));
children.push(new Paragraph({ spacing: { after: 100 }, children: [new TextRun({ text: 'Analysis of public-use microdata: HTOPS_HPS_2603_PUF (released June 2026). Report date: September 7, 2026.', font: FONT, size: 20, color: '52514E' })] }));
children.push(new Paragraph({ spacing: { before: 400, after: 100 }, border: { top: { style: BorderStyle.SINGLE, size: 6, color: '2A78D6', space: 8 } }, children: [new TextRun({ text: 'Reading guide. ', font: FONT, size: 20, bold: true }), new TextRun({ text: 'Every estimate is a weighted population estimate with a standard error from the Census Bureau’s 80 successive-difference replicate weights; unweighted figures are reported alongside because the Bureau has flagged a weighting correction for this wave. Nothing in this report is a causal estimate: the survey is a single cross-section and AI use is self-selected. Findings that run against the prevailing narrative are collected in Section 7.', font: FONT, size: 20 })] }));
children.push(new Paragraph({ children: [new PageBreak()] }));
children.push(new Paragraph({ children: [new TextRun({ text: 'Contents', font: FONT, size: 28, bold: true })], spacing: { after: 160 } }));
for (const c of ['1. Executive summary','2. Data and measurement','3. How much AI use is there?','4. What is AI used for?','5. Who uses AI at work?','6. Intensity and time saved','7. Counterintuitive findings','8. Reconciliation with other estimates','9. Limitations and the distance to causal claims','10. Implications for organizations and careers','Appendix A. Regression tables','Appendix B. Variable construction','Appendix C. Sources']) children.push(new Paragraph({ spacing: { after: 80 }, children: [new TextRun({ text: c, font: FONT, size: 22 })] }));
children.push(new Paragraph({ children: [new PageBreak()] }));

// ---------- 1 Executive summary
children.push(h1('1. Executive summary'));
children.push(p('The March 2026 HTOPS is, to my knowledge, the first federal public-use microdata file in which every employed respondent was asked whether they use artificial intelligence in their own work, for which of eleven task types, how often, and how many hours the tool saved them in the preceding week. Because it is person-level, it lets us do what press-release tables cannot: hold occupation, education, income and telework constant simultaneously, and ask which of the familiar "who uses AI" patterns survive that exercise. Several do not.'));
children.push(p([b('Headline levels. '), 'Among adults who worked for pay in the prior seven days, 52.0 percent (SE 2.0) report having used AI for at least one work task; 36.1 percent (SE 1.8) used it at work in the past week; and 12.4 percent (SE 1.3) used it every day of that week. The "ever" figure is an unbounded recall measure and should be treated as a ceiling; the last-week and daily figures are the ones comparable to the academic literature, and they line up closely with the Real-Time Population Survey (39.2 percent last-week use in Q2 2026) and the Federal Reserve’s synthesis (12 percent daily).']));
children.push(p([b('What the tool is used for. '), 'Use is concentrated in language and information tasks: searching for information or technical help (36.8 percent of all workers), writing communications and documentation (32.4), generating ideas (32.3) and interpreting, translating or summarizing (31.1). "Physical-world" tasks remain marginal: logistics and supply chains (4.5) and medical care (6.1). The median user reports four task types; daily users average 6.4.']));
children.push(p([b('Time saved. '), 'Among last-week users, the modal answer to "how many additional hours would you have needed without AI" is under one hour (25.2 percent); 31.5 percent say one to two hours; 22.2 percent say four or more; 9.8 percent say no time was saved and 3.4 percent say AI cost them time. A midpoint-coded mean of 1.86 hours per last-week user, multiplied by the 36.1 percent last-week usage rate, implies that AI displaced roughly 1.7 percent of aggregate weekly work hours in March 2026, a figure remarkably close to the 2.2 percent that Bick, Blandin and Deming estimate from a different survey for the following quarter.']));
children.push(p([b('Who uses it. '), 'Occupation is the dominant predictor (91 percent of computer workers versus 24 percent in construction, production and transport, and 24 percent in service occupations), followed by education and telework status. But the person-level design reveals that the education and occupation gradients are largely gradients in ', i('where and how one works'), ': among workers who teleworked at least one day, adoption is between 63 and 93 percent in every major occupation group, including construction and services, and between 66 and 86 percent at every education level, including workers without a high-school diploma.']));
children.push(p([b('Seven findings that cut against the narrative (Section 7). '), 'Adoption is flat rather than declining across ages 25 to 64 and is not highest among the youngest workers; men and women adopt at the same rate but men use AI far more intensively; heavy users report the largest time savings, but also the highest share of "it cost me time" responses in exactly the technical occupations that use it most; the South, not the Northeast or West, has the highest conditional adoption; government workers match private-sector workers once composition is controlled; and AI use shows no association with anxiety, depression or loneliness once occupation and demographics are held fixed, despite raw differences that would suggest otherwise.']));
children.push(p([b('Caveats that matter. '), 'The Census Bureau has announced that the March 2026 weights used incorrect (group-quarters-inclusive) county population controls and that a corrected file is forthcoming; I therefore report weighted and unweighted results throughout and find that the substantive conclusions are robust to the choice. The HTOPS is an online panel with a cumulative response rate in the low single digits; its raked weights repair the education skew visible in the raw data (33 percent of the raw sample holds a graduate degree, versus 20 percent weighted) but cannot repair selection on unobservables. The sample is almost entirely metropolitan. Ages are bottom-coded at 25. None of these caveats overturns the findings; all of them bound how far the findings travel.']));

// ---------- 2 Data
children.push(h1('2. Data and measurement'));
children.push(h2('2.1 The survey'));
children.push(p('The Household Trends and Outlook Pulse Survey is the Census Bureau’s successor to the pandemic-era Household Pulse Survey. It is an address-based, web-administered panel: households sampled from the Master Address File complete a baseline questionnaire and are then invited to bimonthly topical waves. The March 2026 wave (file HTOPS_HPS_2603_PUF, dated June 23, 2026) contains 12,521 adult respondents and 219 variables spanning employment, health, food security, housing, transportation, civic participation and institutional trust. Weights are designed to produce national, division-level and large-metro estimates for the household population aged 18 and older.'));
children.push(p('The AI-at-work module was asked of the 6,680 respondents who reported working for pay or profit in the previous seven days. Respondents were shown a definition of AI ("the capability of computational systems to perform tasks typically associated with human intelligence… machine learning, natural language processing, virtual agents, voice recognition") and asked, for each of eleven task types, "IN YOUR WORK, have you used AI to do any of the following tasks?" Those answering yes to any task were asked "AT WORK, how often did you use AI last week?" (every day; at least one day but not every day; used but not last week). Those who used it at least one day were asked "If you had NOT been able to use AI at work last week, how many additional hours would you have needed to complete the same amount of work?" with eight response options ranging from "less than 1 hour" to "more than 4 hours", plus "no time savings" and "required additional time".'));
children.push(p('Two features of the instrument shape everything that follows. First, the task-list question has no reference period, so the "any use" measure captures lifetime use in one’s current or past work and should be read as an upper bound on current engagement. Second, the time-savings item is a counterfactual self-report, which the literature (and the respondents’ own answers) suggests is noisy but not systematically inflated: the modal answer is the smallest positive category, and one in eight users report zero or negative savings.'));
children.push(h2('2.2 Weights, variance and the Bureau’s weighting notice'));
children.push(p('All population estimates use the person weight PWEIGHT. Standard errors use the Bureau’s 80 successive-difference replicate weights with the published formula Var(θ) = (4/80) Σ (θᵣ − θ)², applied to proportions, means, differences and regression coefficients alike; regressions were re-estimated 80 times with each replicate weight. The Bureau’s convention is a 90 percent confidence level, which I follow in figures; tables report standard errors so that readers can apply their own.'));
children.push(p([b('The weighting notice. '), 'The Bureau’s dataset page currently states that "HTOPS weighting for data collected in March and May 2026 incorrectly used county-level ‘residential’ population controls that included Group Quarters," and that corrected data and source-and-accuracy statements will be posted. The corresponding Census "America Counts" story on this module, published in August 2026, was unavailable (HTTP 404) at the time of writing, which is consistent with a pending revision. The practical effect of including group quarters in the controls is to slightly over-weight counties with large institutional populations (prisons, dormitories, barracks, nursing homes). I expect corrected estimates to move by fractions of a percentage point, not by the multiple points that separate the groups compared here. To make that judgment checkable rather than asserted, every table reports the unweighted estimate beside the weighted one, and Appendix A reports both weighted and unweighted regression coefficients.']));
children.push(h2('2.3 Sample composition and response'));
children.push(p('The unweighted sample is older and far more educated than the working population. Among workers, 33 percent of raw respondents hold a graduate degree against 20 percent after weighting; 10 percent hold only a high-school diploma against 27 percent weighted. The weights correct these margins by design, which is why the unweighted "ever used AI" share (62.2 percent) exceeds the weighted share (52.0 percent) by ten points. This gap is a reminder that the raw HTOPS sample would badly overstate adoption; the weighted figures are the ones to quote.'));
children.push(p('The Bureau’s most recent published source-and-accuracy statement (June 2025 wave) reports a cumulative unweighted response rate of 3.5 percent (13.6 percent at baseline recruitment, 25.6 percent at the topical wave). Nonresponse bias analysis is described as ongoing. The sample is 98.8 percent metropolitan (only 78 non-metro workers), so nothing here speaks to rural labor markets. Age is bottom-coded at 25 and top-coded at 88 in the public file; the "25–34" group therefore contains workers aged 18 to 34.'));
children.push(h2('2.4 Analytic definitions'));
children.push(p('Any AI use equals one if a worker answered yes to any of the eleven task items and zero if they answered no to every item they answered; 107 workers who answered no task item are excluded. Last-week use and daily use are defined from the frequency item and set to zero for non-users. Hours saved is coded at category midpoints (0.5, 1, 2, 3, 4), with "more than 4 hours" coded conservatively as 5, "no time savings" as 0 and "required additional time" as −1. A worker teleworked if they reported any telework days. Mental-health items follow the standard PHQ-4 scoring, with GAD-2 ≥ 3 and PHQ-2 ≥ 3 as symptom thresholds. Regressions are weighted linear probability models with heteroskedasticity-robust replicate-weight standard errors; a weighted logit reproduces the sign and significance of every reported coefficient.'));

// ---------- 3 Findings: levels
children.push(h1('3. How much AI use is there?'));
children.push(fig('fig1_funnel.png', 560, 207)); children.push(caption('Figure 1. Three measures of AI use among employed adults, March 2026. Weighted; error bars are 90 percent confidence intervals from replicate weights.'));
children.push(table(T.headline, [4, 1.3, 1, 1.5, 1]));
children.push(note('Table 1. Universe: worked for pay in the past 7 days. Weighted with PWEIGHT; SE from 80 SDR replicate weights. "Ever" has no reference period in the questionnaire.'));
children.push(p('Roughly half of American workers have touched AI in their work; a bit more than a third used it in the survey week; one in eight used it every working day. The ratio between these numbers is itself informative. Among people who have ever used AI at work, 30.4 percent (SE 1.9) did not use it in the past week. Conditional on past-week use, one in three used it daily. Adoption is therefore wide but shallow: a large tried-it population sits around a much smaller core of habitual users. The intensity distribution is also right-skewed in task breadth. Users report a mean of 4.3 task types, but 18 percent report only one, and the distribution has a long tail: daily users report 6.4 task types on average, weekly users 4.4, and lapsed users 2.4.'));
children.push(table(T.freq, [4, 1.3, 1]));
children.push(note('Table 2. Frequency of use among workers who have used AI for at least one work task (n = 4,068).'));
children.push(p('The weighted-versus-unweighted comparison deserves one more sentence. Unweighted last-week use is 46.4 percent against 36.1 weighted; unweighted daily use 15.5 against 12.4. The direction is uniform and the mechanism is composition. Readers who encounter higher HTOPS-based adoption figures in secondary coverage should first ask whether the figures were weighted.'));

// ---------- 4 Tasks
children.push(h1('4. What is AI used for?'));
children.push(fig('fig2_tasks.png', 560, 362)); children.push(caption('Figure 2. Share of workers reporting AI use for each task type, among all workers and among AI users.'));
children.push(table(T.tasks, [4, 1.3, 0.8, 1.3, 0.8]));
children.push(note('Table 3. Item-specific universes differ slightly because of item nonresponse (3–6 percent per item).'));
children.push(p('The task hierarchy is stable across every subgroup I examined: information search leads, followed by the three "text-generation" tasks (writing, summarizing, ideation), then administrative work and data analysis. The four leading tasks are each reported by roughly a third of all workers and by 60 to 71 percent of users. Coding is reported by 11 percent of workers, roughly the sum of computer and engineering occupations plus a thin layer of analysts elsewhere. The two tasks that involve acting on the physical world or on patients, logistics and medical care, remain below 7 percent even though the healthcare occupation group is the third-largest in the workforce. That pattern is consistent with a technology whose current comparative advantage is in producing and transforming text, and whose diffusion into regulated or embodied work is gated by more than user willingness.'));
children.push(p('Occupations differ less in which tasks they use than in how many. Computer workers who use AI report 6.1 task types, management and business workers 5.2, sales workers 4.9, education and arts workers 4.0, healthcare workers 3.5, and construction and service workers 2.3 to 2.6. Depth of use, not the menu, is what separates the frontier occupations.'));

// ---------- 5 Who
children.push(h1('5. Who uses AI at work?'));
children.push(h2('5.1 Descriptive patterns'));
children.push(fig('fig3_occ.png', 560, 345)); children.push(caption('Figure 3. Ever, last-week and daily AI use by occupation group. Farming (n = 21) omitted.'));
children.push(table(T.breakdown, [3.2, 1, 0.8, 1, 1, 0.9, 1.1, 1, 0.8], { groupRows: true, size: 16 }));
children.push(note('Table 4. Weighted estimates; SE in parentheses for the "ever used" column. Hours saved and "no time saved" are among last-week users. Age is bottom-coded at 25 in the public file, so "25–34" includes ages 18–24. Non-metro (n = 78) omitted from region panel.'));
children.push(p('Three gradients dominate the descriptive picture. Occupation runs from 91 percent among computer workers to 24 percent among construction, production and transport workers and in service occupations. Education runs from 15 percent below a high-school diploma to 79 percent with a graduate degree, and the gradient persists inside the user population: graduate-degree users are about 40 percent less likely than high-school users to have lapsed (25 versus 41 percent). Household income runs from 20 to 32 percent in the bottom brackets to 73 percent above $150,000. Telework, which is really a proxy for whether the job is done at a computer, separates a 40 percent world (no telework) from an 80 percent world (any telework).'));
children.push(p('Two gradients that one might expect are weak or absent. The age gradient is not monotone: the 35–44 group has the highest adoption (62 percent), the 25–34 group is lower (48 percent) and statistically indistinguishable from the 55–64 group (50 percent), and only workers 65 and older stand clearly apart (38 percent). The sex gradient in adoption is a statistically insignificant two points. I return to both in Section 7.'));
children.push(table(T.occshare, [3.5, 1.6, 1.6, 1.6]));
children.push(note('Table 5. Composition of the workforce, of AI users and of daily users by occupation group. Weighted.'));
children.push(p('Table 5 reframes the occupational story in terms of where the users are rather than how likely each group is to use. Computer occupations are 7 percent of workers but 26 percent of daily users; management, business, finance and legal occupations are 16 percent of workers and 30 percent of daily users. Together those two groups supply 56 percent of all daily use. Healthcare, by contrast, is 16 percent of the workforce and only 10 percent of daily users.'));
children.push(h2('5.2 Conditional patterns: what survives the regression'));
children.push(p('Appendix Table A1 reports a weighted linear probability model of any AI use on age, sex, race, education, income, class of worker, region, metro status, occupation and telework days. Four results are worth stating in the text.'));
children.push(p([b('Education survives occupation. '), 'Within occupation group and telework status, a graduate degree raises adoption by 30 points (SE 7) relative to less than high school, a bachelor’s by 23, an associate’s by 19 and a high-school diploma by 10. Education is therefore not merely sorting people into AI-exposed occupations; within the same broad occupation it predicts use. The effect is about half the size of the raw gradient, which is the share attributable to sorting.']));
children.push(p([b('Telework survives everything. '), 'Conditional on occupation, education and demographics, teleworking one to two days is associated with 24 points (SE 4) higher adoption, three to four days with 17 points, and five or more with 16 points. The hybrid coefficient exceeding the fully-remote coefficient is a pattern worth noting and probably reflects who hybrid workers are (professionals in large organizations with enterprise licenses) rather than anything causal about the schedule.']));
children.push(p([b('Occupation gaps shrink but do not vanish. '), 'Adding telework cuts the computer-versus-construction gap from 47 points to 36 and the computer-versus-healthcare gap from 32 to 23. Education, social-services and arts occupations become statistically indistinguishable from computer occupations once telework is controlled, which is striking and may reflect the heavy AI exposure of teaching and creative work.']));
children.push(p([b('Income and region retain small independent effects. '), 'Household income above $150,000 adds 9 points and the $25–35k bracket subtracts 16, conditional on everything else; the South adds 11 points relative to the Midwest. Race and ethnicity coefficients are small and insignificant once education and occupation are held constant; the raw Asian advantage (66 percent versus 53 percent White) is a composition effect.']));
children.push(h2('5.3 Telework and the collapse of the occupational gradient'));
children.push(fig('fig4_telework.png', 560, 345)); children.push(caption('Figure 4. Share who have used AI for a work task, by occupation group and whether the worker teleworked at least one day last week. Teleworker cells are small in on-site occupations (construction n = 53, SE 7.6; service n = 32), so those two estimates are directionally solid but imprecise.'));
children.push(fig('fig7_edu_tw.png', 560, 241)); children.push(caption('Figure 5. The same comparison by education. Cell sizes for teleworkers with less than high school and with only a high-school diploma are small (see Table 4 for n).'));
children.push(p('Figures 4 and 5 contain what I consider the most important descriptive result in the file. Among workers who did not telework, adoption spans 21 to 84 percent across occupations and 10 to 73 percent across education levels. Among workers who teleworked at least one day, adoption spans 63 to 93 percent across occupations and 66 to 86 percent across education levels. The construction and production group, with 21 percent adoption among its on-site majority, shows 83 percent among the small minority who telework; sales shows 44 versus 92; healthcare 42 versus 72.'));
children.push(p('The cautious reading is that "teleworked last week" is a marker for the desk-and-screen portion of every occupation group, and that within that portion AI use is now close to universal regardless of credential or job title. The construction teleworker is an estimator or project manager; the healthcare teleworker is a coder, scheduler or telehealth clinician. The uncautious reading, that remote work causes AI adoption, is not supported by anything in a cross-section and should not be drawn. What the data do support is that the widely reported education and occupation gaps in AI use are, to a first approximation, gaps in access to screen-based work. That has a direct implication for HR practice: within the screen-based workforce, the adoption frontier has already been reached and the relevant questions are about depth and quality of use, not access.'));

// ---------- Intensity & time
children.push(h1('6. Intensity and time saved'));
children.push(fig('fig5_hours.png', 560, 241)); children.push(caption('Figure 6. Distribution of self-reported additional hours that would have been needed without AI, among workers who used AI at work at least one day last week (n = 2,991).'));
children.push(table(T.hours, [4, 1.3, 1, 1.5]));
children.push(note('Table 6. Weighted; SE from replicate weights.'));
children.push(p('Time savings are modest and skewed. A quarter of last-week users save less than an hour a week and a further 31.5 percent save one to two hours. At the other end, 22.2 percent report four or more hours, a full half-day. The midpoint-coded mean is 1.86 hours (SE 0.08); coding "more than 4 hours" at 6 rather than 5 raises this to about 2.0. Set against a 40-hour week this is 4.6 percent of a user’s time, and against the whole workforce, 1.7 percent of hours (1.9 percent if one restricts to workers under 65 and uses the higher coding). I regard 1.5 to 2.0 percent of aggregate hours as the defensible range.'));
children.push(p('Time saved rises steeply with frequency and breadth. Daily users report 2.93 hours (SE 0.14) against 1.30 (SE 0.09) for less-than-daily users; users of six or more task types report 2.6 hours against 1.0 for users of a single task type. This is what one would expect from either mechanism at work, learning-by-doing or selection of those who benefit into heavier use, and the cross-section cannot distinguish them. The regression in Appendix Table A3 confirms that frequency dominates: conditional on occupation, telework and demographics, moving from daily to less-than-daily use reduces reported savings by 1.4 hours, while most occupation and education coefficients are small and imprecise.'));
children.push(p([b('The 13 percent who gain nothing. '), 'A non-trivial share of last-week users, 9.8 percent, report no time saved, and 3.4 percent report that AI required additional time. The "required additional time" share is highest precisely in the occupations that use AI most: 5.6 percent of computer workers, 5.9 percent of engineers and scientists and 5.4 percent of management and business workers, against 1 to 2 percent in construction, sales and service occupations. Weekly (not daily) users are nearly twice as likely as daily users to report no saving (15.6 versus 8.8 percent), and workers teleworking three to four days report the highest no-saving share of any telework group (22.8 percent, SE 6.2, an imprecise but large number). The picture is of a technology whose net benefit is heterogeneous and, for a visible minority of sophisticated users, negative in the short run, whether because verification costs exceed drafting savings or because organizations are still mandating experimentation ahead of fit.']));

// ---------- 6 counterintuitive
children.push(h1('7. Counterintuitive findings'));
children.push(p('The following results either contradict widely held priors or contradict what the raw HTOPS tables would suggest. I flag for each whether the finding is robust to weighting and to controls.'));
children.push(numbered([b('The youngest workers are not the leading adopters. '), 'Adoption is 48 percent at ages 25–34 (which includes 18–24 because of bottom-coding), 62 percent at 35–44, 56 percent at 45–54 and 50 percent at 55–64. Conditional on occupation, education and telework, the 35–64 age coefficients are all within a few points of the 25–34 baseline and none is significant; only the 65-and-over group is distinct (−11 points, SE 4.5). Daily use shows the same flat profile through 54. The popular image of AI-at-work as a Gen Z phenomenon is not supported: the workplace adopter is a mid-career professional. Two mechanisms are plausible. The youngest workers are over-represented in service, retail and production jobs that offer no occasion to use AI; and exactly-25 respondents (the bottom-coded group) show 41 percent adoption against 52 percent for ages 26–34, consistent with composition. Consumer AI use may well be highest among the young; workplace AI use is not. Robust to weighting (unweighted pattern is identical).']));
children.push(numbered([b('Men and women adopt at the same rate but use AI very differently. '), 'Adoption is 51 percent for women and 53 for men, a difference well within sampling error. Daily use, however, is 8.8 percent of women versus 16.0 percent of men, and among users 17 versus 30 percent; hours saved among last-week users are 1.46 versus 2.21. Conditional on occupation, education, income and telework, the male coefficient on daily use is +7.0 points (SE 1.8) and on hours saved +0.28 hours (SE 0.13). Among daily users alone, men still report 3.2 hours against women’s 2.3. This pattern, equal entry but unequal depth, matches the emerging experimental and administrative literature on gender gaps in generative-AI engagement and is not explained by the coarse occupation groups available here; finer occupation, task content or organizational norms would be required to unpack it. Robust to weighting and controls.']));
children.push(numbered([b('The heaviest-using occupations are the most likely to say AI cost them time. '), 'The share of last-week users reporting that AI "required additional time" is 5 to 6 percent in computer, engineering and management occupations and about 1 percent in construction, sales and service occupations. Engineers and scientists also report the highest "no time saved" share (20.7 percent). This is the opposite of a naïve learning-curve story in which sophisticated users extract the most value. A better reading is that the technical occupations are using AI for tasks with high verification costs (code, analysis, formal writing) where the drafting saving can be offset by checking, while lighter users deploy it on tasks where the output is consumed as-is. It is also consistent with mandated adoption in technical firms. Sample sizes for the "required additional time" cell are small (112 respondents), so the occupation-specific shares are indicative. The frequency result (weekly users twice as likely as daily users to report zero benefit) is precise and robust.']));
children.push(numbered([b('The South leads, the Midwest lags, and the gap survives controls. '), 'Raw adoption is 57 percent in the South, 56 in the Northeast, 50 in the West and 42 in the Midwest. The prior would be that the coastal regions lead. Conditional on occupation, education, income, telework and metro status, the South remains 11 points (SE 4) above the Midwest while the Northeast and West are statistically indistinguishable from it. The sample is drawn from large metros, so this is a comparison of Dallas, Houston, Atlanta, Miami and Washington with Chicago, not of regions in full; the Washington metro’s federal-contractor and professional-services base likely contributes. I would not build a story on this without the corrected weights, since regional controls are precisely what the Bureau is revising.']));
children.push(numbered([b('Government workers are not laggards. '), 'Raw adoption is 59 percent in government, above the 52 percent in the private sector, and last-week use is close (37 versus 39 percent). Conditional on occupation and education, the government-versus-private difference is small and insignificant in both weighted and unweighted models. Given the concentration of administrative, analytic and educational occupations in the public sector, this is composition rather than culture; but the frequently asserted public-sector AI deficit does not appear in these data. Self-employed workers show the highest conditional adoption (roughly +10 points relative to private employees) but below-average last-week use, consistent with unconstrained experimentation that does not always become routine.']));
children.push(numbered([b('AI use is uncorrelated with mental health, loneliness and social support. '), 'The file contains the PHQ-4, a loneliness item and a social-support item. Raw comparisons show users slightly less anxious and depressed (11.3 versus 12.9 percent above the GAD-2 threshold; 5.8 versus 6.8 percent above the PHQ-2 threshold), with daily users lowest of all (PHQ-4 mean 1.26 versus 1.65 for non-users), and users slightly more likely to report being lonely at least sometimes (28.3 versus 24.7 percent). Every one of these differences is within sampling error, and every one shrinks toward zero once occupation and demographics are controlled (Table 7). Users report higher life satisfaction (7.09 versus 6.64 on a 0–10 scale, z = 2.6), but that difference too becomes insignificant after controls, which identifies it as a socioeconomic gradient rather than anything about the tool. Whatever AI is doing to workers’ wellbeing in early 2026, it is not visible in a cross-sectional comparison of users and non-users with the same job and education.']));
children.push(numbered([b('Institutional trust and economic stress are markers of who adopts, not correlates of adoption. '), 'Users are more trusting of federal statistics (58 versus 49 percent), of statistical agencies, of the police and of the Supreme Court, and less likely to be food-insufficient (2.0 versus 7.6 percent), to rent, or to find price increases "very stressful". None of these survives controls: adjusted coefficients are all small and insignificant. Two exceptions run in an unexpected direction: conditional on everything else, users are marginally more likely to report difficulty getting social support (+5.5 points, z = 1.7) and to express confidence in the presidency and the military (+7 to +8 points, z ≈ 1.7–1.8). I report these for completeness but do not interpret z-statistics below 2 in a study that examines two dozen secondary outcomes.']));
children.push(table(T.secondary, [3.6, 1, 1, 1.2, 0.7, 1.4, 0.7], { size: 16 }));
children.push(note('Table 7. Secondary outcomes by AI use. Raw columns are weighted percentages (means for PHQ-4 and life satisfaction). "Adjusted" is the coefficient on any AI use in a weighted LPM (or linear model) with age, sex, race, education, income, class of worker, region, metro, occupation and telework controls; reported in percentage points (or scale units). Blank adjusted cells were not modeled. All standard errors from replicate weights.'));

// ---------- Benchmarks
children.push(h1('8. Reconciliation with other estimates'));
children.push(p('It is useful to place the HTOPS numbers against the other sources that measure the same quantity, because they use different sampling frames, modes and question wordings.'));
children.push(table([['Source','Period','Measure','Estimate','HTOPS March 2026 comparison'],
 ['Bick, Blandin & Deming, Real-Time Population Survey (FRED Blog, Aug 2026)','Q2 2026','Used generative AI for work last week, ages 18–64','39.2%','36.9% (SE 2.0) for ages under 65; 36.1% all ages'],
 ['Same','Q2 2026','Share of work hours saved','2.2%','≈1.7% (all ages, "more than 4" coded 5); ≈1.9% (under 65, coded 6)'],
 ['Federal Reserve FEDS Note, "Monitoring AI Adoption" (Apr 2026), summarizing RPS','Nov 2025','Used AI at work daily last week','12%','12.4% (SE 1.3)'],
 ['Same','Nov 2025','Used AI at work at least weekly','35.2%','36.1% (SE 1.8)'],
 ['Same, summarizing Gallup','Mid-2025','Daily use','8%','12.4% nine months later'],
 ['Census Bureau story on this module (Aug 2026; page currently unavailable), as quoted in secondary coverage','Mar 2026','Used AI on the job','55%','52.0% (SE 2.0; 90% CI 48.8–55.2)'],
 ['Same','Mar 2026','Users completing tasks 1–2 hours faster','"about a third"','31.5% report 1 or 2 hours'],
 ['Pew Research Center (Mar 2026 summary)','Sep 2025','At least some of own work done with AI','21%','Not comparable (different construct); 36.1% last-week use']], [2.6, 0.9, 1.9, 0.9, 2.4], { size: 16 }));
children.push(note('Table 8. External benchmarks. HTOPS figures from this analysis.'));
children.push(p('The concordance is closer than one would expect from surveys with different frames. The two figures that define the current state of adoption, roughly 36 to 39 percent of workers using AI in a given week and 12 percent daily, are reproduced almost exactly across the RPS and HTOPS, which is reassuring about both. The aggregate time-savings estimate of 1.7 to 2.0 percent of hours sits just below the RPS figure of 2.2 percent for the following quarter, consistent with a series that is growing at roughly a third per year. The 55 percent figure attributed to the Bureau’s own story is three points above my estimate and inside its 90 percent confidence interval; the difference is most plausibly definitional (for example treating item nonresponse differently, or restricting to workers with valid occupation, which yields 53.3 percent here), or reflects the pending weight revision. I would not describe the two as inconsistent.'));

// ---------- Limitations
children.push(h1('9. Limitations and the distance to causal claims'));
children.push(p('Everything in this report is an association in a single cross-section. AI use is chosen, and the people who choose it differ from those who do not in ways that the survey measures only in part. The controls available here, ten occupation groups, seven education categories, seven income brackets and telework days, are coarse; within "management, business, finance and legal" sit both paralegals and chief financial officers. Any conditional coefficient in Appendix A should be read as "the association that remains after adjusting for these coarse observables," not as an effect.'));
children.push(p('The time-savings measure is a counterfactual self-report. Its virtue is that it asks about a specific, recent week and offers a "no savings" and a "cost me time" option, which respondents visibly use. Its weakness is the usual one: people are poor at estimating counterfactual durations, and social desirability may push in either direction. The close agreement with the RPS, which uses different wording, is the best available evidence that the measure is not wildly off.'));
children.push(p('Selection into the survey is the largest threat to external validity. A cumulative response rate in the low single digits, an online mode and a strong education skew mean that the weights are doing heavy lifting. They correct observed margins; they cannot correct the possibility that, within an education-by-age-by-region cell, people who answer a government web survey are more technologically engaged than those who do not. If that is so, all adoption levels here are biased upward by some unknown amount, and the comparison with the RPS (a different online panel) does not resolve it. Relative patterns across groups are less vulnerable than levels.'));
children.push(p('Finally, the weighting notice. I have checked every substantive conclusion against unweighted estimates and found none that depends on the weights; but the reported standard errors and the regional coefficients in particular should be revisited when the corrected file is posted. I recommend re-running the accompanying scripts on the corrected file before any figure from this report is published externally.'));
children.push(p('What would move these findings toward causal claims is the panel structure that HTOPS in principle possesses. The same households are invited to successive waves; if the AI module is repeated in May 2026 and later, within-person changes in use can be related to within-person changes in hours, wellbeing and job loss, with fixed effects absorbing the selection that this report cannot. The May 2026 file is subject to the same weighting revision and was not yet posted at the time of writing.'));

// ---------- Implications
children.push(h1('10. Implications for organizations and careers'));
children.push(p('Three implications follow for practitioners, stated with the caution the evidence warrants.'));
children.push(p([b('The access problem is largely solved for screen-based work; the depth problem is not. '), 'Among teleworkers of every education level and occupation, adoption is a majority behavior. The margin that now separates workers is intensity: daily users report six task types and three hours saved; occasional users report two task types and one hour. Organizational effort is better spent on moving the weekly user to daily, competent use than on first exposure.']));
children.push(p([b('Equal adoption can mask unequal benefit. '), 'The gender pattern (equal entry, half the daily use, two-thirds the time saved) is the clearest example, but the same logic applies to any group. An organization that measures "percent of employees who have used the tool" will see parity that its productivity data will not show. Measuring frequency and self-reported savings, as this survey does, is cheap and far more informative.']));
children.push(p([b('Negative returns are real for a minority and concentrated among sophisticated users. '), 'One user in eight reports no saving or a loss, and the loss is most common in the technical occupations that use AI most. Mandated adoption without attention to task fit is the obvious candidate explanation. The empirical question for any firm is not whether AI saves time on average but for which tasks it costs time, and the honest answer will differ across the two-thirds of users who save under two hours and the fifth who save half a day.']));

// ---------- Appendix
children.push(new Paragraph({ children: [new PageBreak()] }));
children.push(h1('Appendix A. Regression tables'));
children.push(p('All models are weighted linear probability (or linear) models. Standard errors are computed by re-estimating each model with each of the 80 replicate weights and applying the SDR formula. Reference categories: age 25–34; female; Asian; less than high school; $100–150k; family business (class of worker); Midwest; metro; computer occupations; no telework. Stars: * |z| > 1.645, ** |z| > 1.96, *** |z| > 2.576. Farming (n = 21) is retained in the occupation dummies but not interpreted.'));
children.push(h3('Table A1. Any AI use at work (LPM)')); children.push(table(T.reg_any, [3.2, 1.3, 0.9, 0.9, 1.5], { size: 16 }));
children.push(h3('Table A2. Daily AI use at work last week (LPM)')); children.push(table(T.reg_daily, [3.2, 1.3, 0.9, 0.9, 1.5], { size: 16 }));
children.push(h3('Table A3. Hours saved last week among last-week users (linear; "freq" = 1 daily, 2 less than daily)')); children.push(table(T.reg_hours, [3.2, 1.3, 0.9, 0.9, 1.5], { size: 16 }));
children.push(h3('Table A4. Reported no time savings or additional time required, among last-week users (LPM)')); children.push(table(T.reg_nosave, [3.2, 1.3, 0.9, 0.9, 1.5], { size: 16 }));
children.push(h1('Appendix B. Variable construction'));
children.push(table([['Construct','HTOPS variables','Coding'],
 ['Worker (analytic universe)','ANYWORK','= 1 (worked for pay or profit in last 7 days); n = 6,680'],
 ['Any AI use','AIWRK_ADMIN … AIWRK_COMM (11 items)','1 if any item = Yes; 0 if all answered items = No; missing if no item answered (107 cases)'],
 ['Last-week / daily use','AIWRK_FREQ','Last week = codes 1–2; daily = code 1; non-users set to 0'],
 ['Hours saved','AIWRK_HOURS','Midpoints 0.5, 1, 2, 3, 4; "more than 4" = 5; "no time savings" = 0; "required additional time" = −1'],
 ['Occupation','AI_OCC','10 Census-defined groups as labeled in the data dictionary'],
 ['Telework','TWDAYS','Any telework = codes 1–3; days categories as labeled'],
 ['Education / income / class','REDUC, RHHINCOME, CLASS_WORKER','As labeled; "less than grade school" merged with "less than high school"'],
 ['Mental health','ANXIOUS, WORRY, INTEREST, DOWN','Each 0–3; GAD-2 and PHQ-2 sums; symptom threshold ≥ 3; PHQ-4 = sum of four'],
 ['Loneliness / support','SOC_LONELY, SOC_SUPPORT','Lonely often = always/usually; lonely any = always/usually/sometimes; low support = rarely/never'],
 ['Trust','TRUST_FEDSTAT, TRUST_* (9 institutions)','Tend to trust (binary); great deal/quite a lot of confidence (binary)'],
 ['Economic stress','EXPENSE_DIFFICULT, WORKLOSS, PRICESTRESS, PRICECONCERN, TENURE, FD_SUFF','Somewhat/very difficult; any household job-income loss; very stressful; very concerned; renter; sometimes/often not enough food'],
 ['Weights','PWEIGHT, PWEIGHT1–80','Person weight; SDR variance = (4/80) Σ (θᵣ − θ)²']], [2, 2.6, 4], { size: 16 }));
children.push(h1('Appendix C. Sources'));
for (const s of [
 'U.S. Census Bureau, Household Trends and Outlook Pulse Survey, March 2026 Public Use File (HTOPS_HPS_2603_PUF.csv, replicate weights and data dictionary), https://www2.census.gov/programs-surveys/demo/datasets/hhp/2026/topical/HTOPS_HPS_2603_CSV.zip',
 'U.S. Census Bureau, Household Pulse Survey / HTOPS Public Use File page, including the March–May 2026 weighting notice, https://www.census.gov/programs-surveys/household-pulse-survey/data/datasets.html',
 'U.S. Census Bureau, HTOPS June 2025 Source and Accuracy Statement (variance estimation, response rates, coverage), https://www2.census.gov/programs-surveys/demo/technical-documentation/hhp/HTOPS_2506_Source_and_Accuracy.pdf',
 'U.S. Census Bureau, "About a Third of Workers Who Used AI in the Last Week Said They Completed Tasks One to Two Hours Faster," America Counts, August 2026 (page unavailable at time of writing), https://www.census.gov/library/stories/2026/08/ai-use-at-work.html',
 'Board of Governors of the Federal Reserve System, "Monitoring AI Adoption in the U.S. Economy," FEDS Notes, April 3, 2026, https://www.federalreserve.gov/econres/notes/feds-notes/monitoring-ai-adoption-in-the-u-s-economy-20260403.html',
 'FRED Blog, "Does generative AI save time at work?" (Bick, Blandin and Deming Generative AI Adoption Tracker), August 2026, https://fredblog.stlouisfed.org/2026/08/does-generative-ai-save-time-at-work/',
 'Bick, A., Blandin, A. and Deming, D., "The Rapid Adoption of Generative AI," https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4964384',
 'Pew Research Center, "Key findings about how Americans view artificial intelligence," March 12, 2026, https://www.pewresearch.org/short-reads/2026/03/12/key-findings-about-how-americans-view-artificial-intelligence/',
 'Secondary coverage quoting the Census story (55 percent figure): https://glenrhodes.com/us-census-bureau-march-2026-data-55-of-workers-used-ai-on-the-job-one-third-completed-tasks-1-2-hours-faster-and-what-the-productivity-gain-data-actually-means-for-how-organizations-are-using-ai/'
]) children.push(bullet(new TextRun({ text: s, font: FONT, size: 18 })));

const doc = new Document({
  creator: 'Workplace Social Science', title: 'AI at Work: Evidence from the March 2026 HTOPS',
  styles: { default: { document: { run: { font: FONT, size: 22 } } }, paragraphStyles: [
    { id: 'Heading1', name: 'Heading 1', basedOn: 'Normal', next: 'Normal', quickFormat: true, run: { size: 32, bold: true, font: FONT, color: '1F3B63' }, paragraph: { outlineLevel: 0 } },
    { id: 'Heading2', name: 'Heading 2', basedOn: 'Normal', next: 'Normal', quickFormat: true, run: { size: 26, bold: true, font: FONT, color: '2A78D6' }, paragraph: { outlineLevel: 1 } },
    { id: 'Heading3', name: 'Heading 3', basedOn: 'Normal', next: 'Normal', quickFormat: true, run: { size: 22, bold: true, font: FONT, color: '0B0B0B' }, paragraph: { outlineLevel: 2 } } ] },
  numbering: { config: [ { reference: 'bul', levels: [{ level: 0, format: LevelFormat.BULLET, text: '•', alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 540, hanging: 270 } } } }] },
                         { reference: 'num', levels: [{ level: 0, format: LevelFormat.DECIMAL, text: '%1.', alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 540, hanging: 360 } } } }] } ] },
  sections: [{ properties: { page: { size: { width: 12240, height: 15840 }, margin: { top: 1300, bottom: 1200, left: 1440, right: 1440 } } },
    footers: { default: new Footer({ children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: 'AI at Work: March 2026 HTOPS   |   Page ', font: FONT, size: 16, color: '52514E' }), new TextRun({ children: [PageNumber.CURRENT], font: FONT, size: 16, color: '52514E' })] })] }) },
    children }]
});
Packer.toBuffer(doc).then(buf => { fs.writeFileSync('reports/AI_at_Work_HTOPS_March2026_Report.docx', buf); console.log('written'); });
