const fs = require('fs');
const { Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell, WidthType, ImageRun, AlignmentType, BorderStyle, ShadingType, PageBreak, Footer, PageNumber, LevelFormat, PageOrientation } = require('docx');
process.chdir(require('path').join(__dirname,'..'));
const T = JSON.parse(fs.readFileSync('data/derived/gtables.json'));
const FONT = 'Calibri';
const p = (text) => new Paragraph({ spacing: { after: 120, line: 276 }, children: (Array.isArray(text) ? text : [text]).map(t => typeof t === 'string' ? new TextRun({ text: t, font: FONT, size: 22 }) : t) });
const b = (t) => new TextRun({ text: t, bold: true, font: FONT, size: 22 });
const i = (t) => new TextRun({ text: t, italics: true, font: FONT, size: 22 });
const h1 = (t) => new Paragraph({ heading: HeadingLevel.HEADING_1, spacing: { before: 360, after: 160 }, children: [new TextRun({ text: t, font: FONT })] });
const h2 = (t) => new Paragraph({ heading: HeadingLevel.HEADING_2, spacing: { before: 280, after: 120 }, children: [new TextRun({ text: t, font: FONT })] });
const h3 = (t) => new Paragraph({ heading: HeadingLevel.HEADING_3, spacing: { before: 200, after: 80 }, children: [new TextRun({ text: t, font: FONT })] });
const numbered = (runs) => new Paragraph({ numbering: { reference: 'num', level: 0 }, spacing: { after: 100 }, children: (Array.isArray(runs) ? runs : [runs]).map(t => typeof t === 'string' ? new TextRun({ text: t, font: FONT, size: 22 }) : t) });
const caption = (t) => new Paragraph({ spacing: { before: 60, after: 200 }, children: [new TextRun({ text: t, font: FONT, size: 18, italics: true, color: '52514E' })] });
const note = (t) => new Paragraph({ spacing: { before: 40, after: 240 }, children: [new TextRun({ text: t, font: FONT, size: 17, color: '52514E' })] });
const fig = (file, w, h) => new Paragraph({ alignment: AlignmentType.CENTER, spacing: { before: 120, after: 40 }, children: [new ImageRun({ type: 'png', data: fs.readFileSync('charts/'+file), transformation: { width: w, height: h } })] });
function table(rows, widths, opts = {}) {
  const TOTAL = opts.total || 9360; const sum = widths.reduce((a, c) => a + c, 0); const cw = widths.map(x => Math.round(x / sum * TOTAL));
  const bd = { style: BorderStyle.SINGLE, size: 4, color: 'D8D6CF' };
  return new Table({ width: { size: TOTAL, type: WidthType.DXA }, columnWidths: cw, rows: rows.map((r, ri) => new TableRow({ tableHeader: ri === 0, children: r.map((c, ci) => {
    const isHead = ri === 0; const isGroup = opts.groupRows && r.slice(1).every(x => x === '');
    return new TableCell({ width: { size: cw[ci], type: WidthType.DXA }, borders: { top: bd, bottom: bd, left: { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' }, right: { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' } },
      shading: isHead ? { type: ShadingType.CLEAR, fill: 'EEF3FA', color: 'auto' } : (isGroup ? { type: ShadingType.CLEAR, fill: 'F5F4F0', color: 'auto' } : undefined), margins: { top: 40, bottom: 40, left: 70, right: 70 },
      children: [new Paragraph({ alignment: ci === 0 ? AlignmentType.LEFT : AlignmentType.RIGHT, spacing: { after: 0 }, children: [new TextRun({ text: String(c), font: FONT, size: opts.size || 17, bold: isHead || isGroup })] })] }); }) })) });
}
const C = [];
C.push(new Paragraph({ spacing: { before: 1000, after: 200 }, children: [new TextRun({ text: 'The Gender Gap in AI at Work', font: FONT, size: 48, bold: true })] }));
C.push(new Paragraph({ spacing: { after: 200 }, children: [new TextRun({ text: 'Addendum to "AI at Work in the United States": a deep dive into sex differences in adoption, intensity, task mix and time saved, with a full weighted-versus-unweighted comparison', font: FONT, size: 26, color: '52514E' })] }));
C.push(new Paragraph({ spacing: { after: 100 }, children: [new TextRun({ text: 'Source: Census Bureau Household Trends and Outlook Pulse Survey, March 2026 public-use file (HTOPS_HPS_2603_PUF). Prepared for Workplace Social Science, September 7, 2026.', font: FONT, size: 20, color: '52514E' })] }));
C.push(new Paragraph({ spacing: { before: 300, after: 100 }, border: { top: { style: BorderStyle.SINGLE, size: 6, color: '2A78D6', space: 8 } }, children: [new TextRun({ text: 'Reading guide. ', font: FONT, size: 20, bold: true }), new TextRun({ text: 'Every gap is reported as male minus female. Weighted estimates use PWEIGHT with successive-difference replicate standard errors; unweighted estimates use ordinary least squares with heteroskedasticity-robust standard errors. Because the Bureau has flagged a pending correction to this wave’s weights, the two are shown side by side in every table. Stars mark |z| above 1.645 (*), 1.96 (**) and 2.576 (***). All results are associations in a single cross-section.', font: FONT, size: 20 })] }));
C.push(new Paragraph({ children: [new PageBreak()] }));

C.push(h1('1. Summary'));
C.push(p('The main report noted that men and women adopt AI at work at the same rate but that men use it far more intensively. This addendum asks whether that pattern survives the fullest set of controls the HTOPS allows, where in the workforce it lives, and how much the answer depends on the survey weights. The short answer is that the intensity gap is one of the most robust findings in the file and the adoption gap is one of the least.'));
C.push(p([b('Adoption: no robust gap. '), 'Weighted, 51.0 percent of employed women and 53.1 percent of employed men have used AI for a work task, a difference of 2.1 points with a standard error of 3.6. Unweighted, the gap is 6.1 points and statistically significant. The two disagree because the weights move 15 percent of the male sample into construction, production and transport occupations (from 15 to 30 percent of men), where adoption is lowest. Once occupation is controlled, weighted and unweighted converge on a conditional male advantage of 3.5 to 4.7 points, marginally significant. A Kitagawa-Oaxaca-Blinder decomposition shows why the raw weighted gap is so small: women are, in composition, positioned to adopt ', i('more'), ' than men (they are more concentrated in education, healthcare, office and management work, and are slightly more educated), so composition contributes about −7 points and the unexplained component about +5. Women’s occupational position masks a within-occupation gap.']));
C.push(p([b('Intensity: a large, stable, unexplained gap. '), 'Daily use is 8.8 percent of employed women against 16.0 percent of men, a 7.2 point gap (SE 2.3) that is 8.2 points unweighted. Across six specifications from raw to a kitchen sink of twenty controls (age, race, region, metro, education, income, occupation, sector, telework days, marital status, children by age band, household size, insurance, disability, cognitive difficulty, home language, PHQ-4 and life satisfaction), the weighted coefficient never leaves the range 6.6 to 7.5 and the unweighted never leaves 6.1 to 8.2. The decomposition assigns essentially all of it (over 100 percent weighted, about 70 percent unweighted) to the unexplained component. Among users, the gap is larger still: 17 percent of female users are daily users against 30 percent of male users. Men also use AI for more task types (4.7 versus 3.9 among users), a gap of 0.7 to 0.8 task types that controls barely touch.']));
C.push(p([b('Time saved: mostly composition and frequency. '), 'The raw weighted gap in hours saved among last-week users is large, 0.75 hours (2.21 versus 1.46), but it is 0.40 unweighted, and it shrinks to 0.22 to 0.28 hours with controls in both. Between half and two-thirds of the weighted gap is explained, mainly by men’s higher frequency of use and their occupational mix; the residual quarter-hour is significant unweighted (z ≈ 2.6) and marginal weighted (z ≈ 1.7). The gap in reporting a half-day or more saved (4+ hours: 31 versus 12 percent weighted) is likewise mostly composition; it falls to 3 to 5 points with controls.']));
C.push(p([b('Where the gap lives. '), 'The intensity gap is positive in nearly every subgroup. It is largest in computer occupations (24 points, both weighted and unweighted), among fully remote workers (17 points) and among the graduate-educated (14 points), and it is present among workers with no telework (6 points), no children (8 points) and every age band. It is not explained by parenthood: the gap among parents of children under five is, if anything, smaller than among non-parents in the weighted data (2 versus 8 points, imprecise) and about the same in the unweighted data; interaction terms for children of any age are small and insignificant. The only subgroup with a reversed sign, office and administrative support, rests on 136 men and is not reproduced unweighted.']));
C.push(p([b('Task mix: the gap is in what men add, not in what women do. '), 'Among users, women and men report the "language" tasks at nearly identical rates: writing communications (61 versus 64 percent), generating ideas (61 versus 63), administrative work (51 versus 54). The male surplus is concentrated in four tasks: searching for information or technical help (+18 points), coding or modeling (+18), data analysis and visualization (+17) and tutoring or training (+13). Conditional on occupation, education and telework, these four gaps remain 9 to 15 points and significant in both weightings. Customer support, medical care and logistics show no gap.']));
C.push(p([b('Do the weights matter? '), 'For the intensity results, no: every conclusion about daily use, task breadth and task mix holds under both weightings, under all 80 replicate weightings, and under weights trimmed at the 99th or 95th percentile. For the raw adoption gap and the raw hours gap, yes: the weights change the first from significant to null and inflate the second by almost half. Both sensitivities disappear once occupation is controlled, which is the operational lesson: any gender comparison from this file should condition on occupation before it is quoted. A separate and more general warning is that the HTOPS weights are extremely dispersed. The top 1 percent of respondents carry 20 percent of the population weight and the top 10 percent carry 60 percent; the Kish design effect from weight variation alone is about 8, so the effective sample of 6,680 workers behaves like roughly 800 for the purpose of sampling error. This is why weighted standard errors are two to three times the unweighted ones and why weighted subgroup estimates that rest on a few heavily weighted respondents (young, less educated, blue-collar) should be treated with particular caution.']));

C.push(h1('2. Levels and raw gaps'));
C.push(table(T.raw, [3.2, 0.9, 0.9, 0.9, 0.7, 0.9, 0.9, 0.9, 0.7, 1.0], { size: 15 }));
C.push(note('Table 1. Gaps are male minus female. Weighted (w) columns use PWEIGHT; SE from 80 SDR replicate weights. Unweighted (unw) SE is the two-sample standard error. Percent for binary outcomes; count for task types; hours for hours saved. "Users" are workers who have used AI for any work task; "last-week users" used it at least one day in the survey week.'));
C.push(p('Two things stand out before any control is applied. The adoption and last-week-use gaps are small and imprecise weighted but clear unweighted, while the daily-use, task-breadth and hours gaps are clear under both weightings. And the hours gap is the one place where the weights change a magnitude substantially rather than merely a significance level: 0.75 hours weighted against 0.40 unweighted. Section 6 shows that this is driven by a handful of heavily weighted male respondents in the "more than 4 hours" category, and that the conditional estimates agree.'));

C.push(h1('3. The specification ladder'));
C.push(fig('g1_ladder.png', 560, 276)); C.push(caption('Figure 1. Male−female gap under six nested specifications. Circles: weighted with replicate-weight 90 percent intervals. Squares: unweighted with robust 90 percent intervals. Hours models also control for frequency of use.'));
C.push(p('Each row of the ladder adds a block of controls to a weighted linear probability model (or linear model) of the outcome on a male indicator. The blocks are ordered from least to most plausibly "post-treatment": demographics and geography first, then human capital, then job characteristics, then family structure, then health and wellbeing. Controls in the last two blocks could themselves be affected by AI use or by the same unobservables that drive it, so the labor-market specification (row 4) is the headline and rows 5 and 6 are robustness.'));
C.push(h3('Table 2a. Any AI use at work (percentage points)')); C.push(table(T.ladder_any_ai, [3.4, 1.2, 0.8, 1.2, 0.8, 0.8]));
C.push(h3('Table 2b. Used AI at work last week')); C.push(table(T.ladder_ai_lastweek, [3.4, 1.2, 0.8, 1.2, 0.8, 0.8]));
C.push(h3('Table 2c. Used AI every day last week')); C.push(table(T.ladder_ai_daily, [3.4, 1.2, 0.8, 1.2, 0.8, 0.8]));
C.push(h3('Table 2d. Number of task types, among users')); C.push(table(T.ladder_ntasks, [3.4, 1.2, 0.8, 1.2, 0.8, 0.8]));
C.push(h3('Table 2e. Hours saved last week, among last-week users (controls for frequency from row 2)')); C.push(table(T.ladder_hrs_saved, [3.4, 1.2, 0.8, 1.2, 0.8, 0.8]));
C.push(h3('Table 2f. Saved four or more hours, among last-week users')); C.push(table(T.ladder_big_saving, [3.4, 1.2, 0.8, 1.2, 0.8, 0.8]));
C.push(note('Reference categories as in the main report. Sample sizes fall down the ladder because of item nonresponse on added controls. Re-estimating the raw gap on the kitchen-sink sample gives −1.4 points (weighted) and +5.7 (unweighted) for any use and +6.4 and +8.7 for daily use, so sample attrition moves the weighted adoption gap by about 3 points and the daily gap by less than 1; the conditional estimates in rows 4 to 6 are all on near-identical samples.'));
C.push(p([b('Reading the ladder. '), 'For any use, the weighted gap is flat at about 2 points through the human-capital block and then rises to 4 to 5 points when occupation is added, because women are in more AI-exposed occupations; the unweighted gap falls from 6 to 3 or 4 for the mirror-image reason (the unweighted sample under-represents blue-collar men). The two weightings disagree about the raw gap and agree about the conditional one. For daily use the picture is simpler: nothing moves it. Adding twenty controls changes the weighted coefficient from 7.2 to 7.5 and the unweighted from 8.2 to 6.2. For hours saved, the demographic block alone removes 40 percent of the weighted gap (a few heavily weighted young men report very large savings), the labor-market block removes another third, and the family and health blocks do little; the conditional gap of roughly a quarter hour is stable across the last three rows in both weightings.']));

C.push(h1('4. Decomposition: composition versus the unexplained residual'));
C.push(table(T.kob, [3.6, 0.9, 1.2, 1.0, 0.9, 3.4], { size: 15 }));
C.push(note('Table 3. Kitagawa-Oaxaca-Blinder decomposition using pooled coefficients (Neumark). "Explained" is the part of the gap attributable to men and women having different distributions of the covariates; "unexplained" is the part attributable to different outcomes at the same covariate values. Labor-market controls: age, race, region, metro, education, income, occupation, sector, telework (plus frequency for hours). Kitchen sink adds marital status, children by age, household size, insurance, disability, cognitive difficulty, home language, PHQ-4 and life satisfaction. Contributions in percentage points except task types (count) and hours.'));
C.push(p('The decomposition sharpens the ladder. For any use, composition works against a male advantage: in the weighted data women’s occupations, education and telework patterns would predict 7 points higher adoption for women, and the unexplained component of about +5 points offsets it. For daily use, composition contributes roughly nothing weighted (−1 point) and about 2.5 points unweighted (occupation and income), leaving 6 to 7.5 points unexplained under every specification. For task breadth, composition explains 0.1 to 0.2 of a 0.7 to 0.9 task-type gap. For hours, composition explains more than half, and the single largest term is frequency of use: men save more hours largely because they use the tool more days.'));
C.push(p('"Unexplained" is not a synonym for discrimination, preference or skill. It is the part of the gap that the ten occupation groups, seven education categories and the rest of the HTOPS covariates cannot account for. Finer occupation codes, task content, employer size, industry, hours worked and the presence of an enterprise AI license are all absent from this file and any of them could absorb part of the residual. What the decomposition rules out is the two most common explanations offered in commentary: the intensity gap is not a job-sorting story and it is not a parenthood story.'));

C.push(h1('5. Where the gap lives'));
C.push(fig('g3_het.png', 520, 528)); C.push(caption('Figure 2. Male−female gap in daily AI use within subgroups. Weighted with 90 percent replicate-weight intervals; unweighted point estimates as squares. Groups shown only where both sexes have at least 100 respondents.'));
C.push(table(T.het, [2.6, 1.4, 0.7, 1.4, 0.5, 0.7, 1.4, 0.7, 1.1], { size: 14, groupRows: true }));
C.push(note('Table 4. Within-group levels and gaps. Hours are shown only where at least 50 last-week users of each sex are available. Groups with fewer than 100 respondents of either sex are omitted (farming; engineering; less than high school; some income and marital-status cells).'));
C.push(p([b('Occupation. '), 'The intensity gap scales with how AI-intensive the occupation is. In computer occupations, 32 percent of women and 56 percent of men use AI daily, a 24 point gap reproduced almost exactly unweighted (24.5). In management, business, finance and legal occupations the weighted gap is 17 points but only 3.5 unweighted, a disagreement large enough that I would report the range rather than either number. In healthcare, sales and education the gap is 5 to 8 points and consistent across weightings. In service occupations both sexes are near zero. The office and administrative support cell is the one reversal (women 20 percent daily, men 3.5 percent, weighted), but it rests on 136 men, its unweighted gap is +0.6, and its 90 percent interval spans 30 points; I do not believe it.']));
C.push(p([b('Telework. '), 'The gap widens with telework intensity: 6 points among non-teleworkers, 7 among hybrid one-to-two-day workers, 17 among three-to-four-day and fully remote workers. Both weightings agree on the shape. Since remote workers are near-universal adopters (Section 5.3 of the main report), this says that among people who all have access, men are considerably more likely to make AI a daily habit. The male-by-telework interaction in a fully controlled model is, however, not significant weighted (−3 points, SE 5) and only modestly so unweighted (+5, SE 2), so the descriptive gradient should not be over-read.']));
C.push(p([b('Age and parenthood. '), 'The gap is present in every age band, largest at 45 to 54 (11 points, both weightings) and at 25 to 34 unweighted (14.5), smallest at 35 to 44 weighted (4 points). It is not larger among parents of young children. Weighted, the gap is 2 points among workers with a child under five and 8 points among workers with no children; unweighted, 13 and 6.5. The male-by-child-under-five interaction is +1 point (SE 4) weighted and +5 (SE 3) unweighted, and the male-by-any-child interaction is +2 and +3, none significant. Whatever the time-squeeze account of gender gaps in technology use has going for it elsewhere, it does not explain the daily-use gap here.']));
C.push(p([b('Education, income and race. '), 'The gap is largest among the graduate-educated (14 points weighted, 10 unweighted) and bachelor’s-educated (10 and 11), smallest among high-school graduates (2 and 0). It is largest in the top income bracket (11 and 9). Among Asian workers the gap is 15 points under both weightings, twice the White gap (7 and 8); among Black workers it is zero weighted and 6 unweighted, with wide intervals. The intensity gap, in other words, is a phenomenon of the professional, credentialed, high-income workforce where AI is most available.']));
C.push(h3('Table 5. Interaction tests (fully controlled models)')); C.push(table(T.inter, [2.6, 0.7, 0.5, 0.7, 0.5, 0.7, 0.5, 0.7, 0.5, 0.7, 0.5, 0.7, 0.5], { size: 13 }));
C.push(note('Coefficient on the interaction between the male indicator and the named characteristic, from the labor-market specification (row 4 of the ladder) plus the characteristic’s main effect where not already absorbed. Percentage points for use outcomes; hours for hours saved. The only interaction that is significant under both weightings is male × computer occupation for daily use (+17 weighted, +21 unweighted).'));

C.push(h1('6. What men and women use AI for'));
C.push(fig('g2_tasks.png', 560, 310)); C.push(caption('Figure 3. Share of AI users reporting each task type, by sex. Weighted.'));
C.push(table(T.tasks, [2.6, 1, 1, 0.8, 0.6, 1.2, 1.2, 1.2], { size: 15 }));
C.push(note('Table 6. Among users unless noted. Conditional gap is the male coefficient in a model with age, race, region, metro, education, income, occupation, sector and telework controls, estimated on users. Last column is the raw gap among all workers, users and non-users together.'));
C.push(p('The task table is, to my mind, the most interpretable result in this addendum. On the tasks that dominate AI use overall, writing, ideation, summarizing and administration, women and men who use AI report them at the same rates. The male surplus in task breadth comes from four tasks with a distinctly technical or self-directed character: searching for technical help, coding, data analysis and tutoring or training oneself. Conditional on occupation and education, these gaps are 9 to 15 points and significant under both weightings; the search gap in particular (15 points weighted, 8.5 unweighted) is not an artifact of men being in technical jobs, since it survives occupation controls and is present within education, healthcare and management occupations. One reading is that men are more likely to treat the tool as a general-purpose assistant to be consulted for anything, while women’s use is more often confined to the specific writing tasks for which it was introduced. The data cannot distinguish preference from exposure, and a plausible alternative is that the search, coding and analysis tasks are the ones most tied to informal peer learning, which is itself gendered in many workplaces.'));

C.push(h1('7. How much do the weights matter?'));
C.push(fig('g4_weights.png', 560, 224)); C.push(caption('Figure 4. Concentration of person weights among employed respondents.'));
C.push(table(T.wdiag, [4, 3], { size: 16 }));
C.push(note('Table 7. Weight diagnostics for the worker sample. The Kish design effect is 1 + CV² of the weights and approximates the inflation of sampling variance from unequal weighting alone.'));
C.push(p('Three separate questions hide under "do the weights matter," and they have different answers.'));
C.push(numbered([b('Do weighted and unweighted point estimates differ? '), 'For raw gender gaps in adoption and hours, yes, by amounts that change the qualitative story (2 versus 6 points; 0.75 versus 0.40 hours). The reason is transparent in the composition table (Appendix Table A1): the weights roughly double the share of men in construction, production and transport, halve the share of both sexes with a graduate degree, and more than double the share of workers aged 25 to 34. Once occupation and education are controlled, the two agree to within a point or a tenth of an hour on every outcome. For the daily-use and task-breadth gaps, weighted and unweighted agree even without controls.']));
C.push(numbered([b('Could the pending weight correction change the results? '), 'The Bureau’s error concerns county population controls that included group quarters. Correcting it will re-rake the weights to slightly different totals; it will not change who is in the sample or what they answered. The 80 replicate weights are themselves 80 alternative weightings of the same respondents, each perturbing the raking, and across all of them the daily-use gap ranges from 3.9 to 10.1 points, never approaching zero. Trimming the heaviest weights at the 99th or 95th percentile moves the gap by less than half a point. I would be surprised if a corrected file moved any conditional estimate in this addendum by more than its standard error.']));
C.push(numbered([b('Are the weighted estimates reliable? '), 'This is the question that deserves more attention than it usually gets. The HTOPS weights are extraordinarily dispersed: the median worker weight is about 6,600 and the maximum is 1.85 million, and the respondents carrying the largest weights are overwhelmingly young, high-school-educated and in blue-collar or service jobs, exactly the cells where the online panel under-recruits. A design effect near 8 means weighted standard errors are two to three times unweighted ones and that any weighted subgroup estimate for the young or less-educated is effectively an estimate from a few dozen people. The unweighted estimates are precise but describe a sample that is older, more educated and more professional than the workforce. Neither is "right"; the conditional estimates, which agree, are the ones to quote, and the honest description of the raw adoption gap is "between 2 and 6 points, depending on how one weights a sample that under-represents blue-collar men."']));

C.push(h1('8. Interpretation and limits'));
C.push(p('The pattern this file shows, equal entry and unequal depth, matches what has been reported from other settings: field experiments and administrative data on generative-AI tools have found women less likely to use them when use is optional and less likely to use them intensively, with the gap narrowing when use is required or explicitly sanctioned. The HTOPS adds three things to that picture. It shows the pattern in a national probability sample of the employed population rather than in a single firm or platform. It shows that the gap is not a job-sorting artifact, since it persists within coarse occupation groups and is largest in the most AI-intensive ones. And it shows that the gap is not a parenthood or time-budget artifact, since it is no larger among parents of young children and does not respond to family controls.'));
C.push(p('What the file cannot do is say why. The residual gap is consistent with differences in confidence, in perceived legitimacy of using AI at work, in informal peer networks through which technical uses spread, in employer-provided training, and in the gender composition of the specific jobs within each broad occupation group. It is also consistent with reporting differences, if men are more inclined to describe occasional use as daily or to round hours saved upward; the survey offers no way to check. A repeated AI module in later HTOPS waves, with the panel structure the survey already has, would allow within-person analysis and would at least separate stable individual differences from changes over time.'));
C.push(p('For practitioners the operational finding is narrower and firmer. Measuring "share of employees who have tried the tool" will show gender parity in most organizations; measuring frequency, task breadth and time saved will not. If an organization’s productivity case for AI rests on daily, broad, self-directed use, and the data suggest that it does, then a parity metric based on trial use is measuring the wrong thing, and the four tasks where the gap concentrates (search, analysis, coding, self-training) are where targeted enablement would be tested first.'));

C.push(h1('9. Is it the work or the tool? Within-occupation task gaps'));
C.push(p('A natural objection to Section 6 is that women use AI for coding and analysis less because their jobs involve less coding and analysis. The HTOPS asks what workers use AI for, not what their jobs consist of, so it cannot settle this directly. The closest available test is to compare women and men inside the same broad occupation group, where the task content of the work is at least similar. Table 9 does so for the six tasks with the largest overall gaps, among AI users, in every occupation group with at least 50 users of each sex.'));
C.push(table(T.tasks_within_occ, [3.2, 1.1, 1.1, 0.9, 0.7, 0.9, 1.0], { size: 15, groupRows: true }));
C.push(note('Table 9. Share of AI users reporting each task, by sex, within occupation group. Weighted with replicate-weight SEs; unweighted gap for comparison. Cells are small (as few as 52 women in service occupations, 70 in engineering), and the weighted and unweighted gaps disagree in several cells; read the direction, not the second digit.'));
C.push(p('Coding is the cleanest case. In computer occupations, 60 percent of female users and 78 percent of male users use AI for coding (44 versus 70 unweighted), and the gap is of similar size in engineering, education, healthcare, management and sales. Technical search shows a male surplus in most groups, but the computer-occupation estimate (68 versus 95 weighted, 83 versus 92 unweighted) is imprecise and depends on the weights. Writing communications and generating ideas show no consistent gap within occupations, and in office, sales and service occupations women lead on ideation. The pattern is what the aggregate task table suggested: the same writing tasks, with a male surplus concentrated in coding, analysis and self-training that persists inside the occupations where those tasks are the job.'));
C.push(p('This does not close the question. The ten occupation groups are broad; "computer occupations" contains software engineers alongside support, testing and product roles, and women are over-represented in the latter. Part of the within-group coding gap could be within-group role sorting. Settling it would take detailed occupation codes or a direct question about time spent on each task, neither of which the HTOPS has.'));

C.push(h1('10. What the task-level literature adds'));
C.push(p('Bick, Blandin, Deming and Schumacher (2026) measure AI adoption at the task level in the Real-Time Population Survey, showing each of roughly 14,000 workers (ages 18 to 64, four waves from August 2025 to May 2026) the ten most important tasks in their own occupation and asking which they perform and which AI helps with. Three of their results bear on the gender gap here.'));
C.push(p([b('Demographics explain little variance; that is not the same as small gaps. '), 'In their Table 4, task fixed effects alone explain 11.2 percent of the variation in whether a worker uses AI for a given task; adding education, race, sex and a quadratic in age raises this to 12.7 percent; adding individual fixed effects raises it to 44.0 percent. Sex enters only as a control, and no sex coefficient is reported. A 7-point difference in daily use between two groups of roughly equal size explains well under one percent of variance, so their finding and the stable gap in Section 3 are compatible. What their result establishes is that most of the action is between individuals doing the same task, which is also where the HTOPS gap lives.']));
C.push(p([b('Experience widens breadth, but by less than the gender gap. '), 'Their Table 5 finds that users who were already using AI six months before the survey use it for 0.43 more tasks (SE 0.11), against a mean of 4.7, controlling for detailed occupation, sex, age and total tasks performed; the authors note that part of this reflects selection of early adopters. Two instrumented tests (cross-task spillovers, with 2SLS coefficients of 0.55 to 0.70, and a work-to-home spillover of 0.50) support a learning interpretation. Applied to the HTOPS, the gender gap in task breadth among users is 0.78 task types. Even if every male user and no female user had six months of experience, their point estimate would account for 0.43 of that; with a plausible 15 to 25 point difference in experience shares, it accounts for about a tenth. Their proxy is coarse and longer experience presumably matters more, so this is a lower bound, but experience timing is a contributor to the breadth gap, not its explanation.']));
C.push(p([b('The gap sits on the frontier tasks, and spillovers compound it. '), 'Their highest-adoption tasks are reading documents for technical information (61 percent of workers doing that task use AI for it), preparing research reports (61) and analyzing data to identify trends (58), which correspond to the HTOPS tasks with the largest gender gaps, technical search and data analysis. Their spillover estimates imply that adoption on one task raises adoption on a worker\u2019s other tasks by more than half a point per point. A difference in where two groups start therefore propagates across the task portfolio without any difference in the work itself, which is one mechanism that could produce the within-occupation pattern in Table 9.']));
C.push(p([b('Occupation-level frictions fall on female-dominated clerical work. '), 'Their Table 3 lists the occupations where exposure scores most over-predict adoption: receptionists (7.6 percent actual against 54 predicted), medical secretaries (16.8 against 61), tellers, customer service representatives, data entry keyers and insurance clerks, all heavily female. The most under-predicted are construction equipment operators, equipment repairers and industrial electricians, all heavily male. The authors attribute the over-prediction to adoption costs and task frictions: standardized workflows, compliance rules, restrictions on confidential data. That is a workplace-level reason for a raw gender gap in a full-workforce sample. It does not explain the within-occupation gap here, but it argues against reading any raw gap as a statement about individual women.']));
C.push(p('Reference: Bick, A., Blandin, A., Deming, D. J., and Schumacher, T. (2026). "What Work Does Generative AI Do?" Federal Reserve Bank of St. Louis Working Paper 2026-017A, August 25, 2026 version. https://doi.org/10.20955/wp.2026.017'));

C.push(new Paragraph({ children: [new PageBreak()] }));
C.push(h1('Appendix A. Composition of the male and female workforce'));
C.push(table(T.comp, [3.4, 1.2, 1.2, 1.2, 1.2], { size: 15, groupRows: true }));
C.push(note('Table A1. Column percentages within sex, among workers with a valid response on each characteristic (3 to 4 percent of workers lack a valid occupation code). Weighted (w) and unweighted (unw). The weighted-unweighted differences here are what drive the differences in raw gaps in Table 1.'));
C.push(h1('Appendix B. Method notes'));
C.push(p('Sample. Workers are respondents who worked for pay or profit in the previous seven days (n = 6,680; 3,071 women and 3,609 men). Sex is the edited binary ESEX. Users are workers reporting any of the eleven task types (n = 4,091); last-week users are those reporting use on at least one day in the survey week (n = 2,991).'));
C.push(p('Estimation. Weighted models are estimated by weighted least squares with PWEIGHT; standard errors are obtained by re-estimating with each of the 80 replicate weights and applying the successive-difference formula Var = (4/80) Σ (θᵣ − θ)². Unweighted models use ordinary least squares with HC1 robust standard errors. Linear probability models are used throughout for comparability across specifications and for the decomposition; a weighted logit reproduces the sign and significance of every daily-use coefficient. The decomposition uses pooled coefficients from a model that includes the male indicator (Neumark 1988), with categorical contributions summed within variable.'));
C.push(p('Controls. Age band (25–34 including bottom-coded 18–24; 35–44; 45–54; 55–64; 65+); race/ethnicity (five groups); region; metro status; education (six groups); household income (seven brackets); occupation (ten groups); class of worker (five); telework days (four); marital status (married, never married, divorced/widowed/separated); children in household under 5, 5–11 and 12–17 (each binary; households without children coded zero); household size (1–5+); insurance type (employer, uninsured, other); any serious functional difficulty (a lot of difficulty or cannot do, across six domains); any cognitive difficulty; language other than English at home; PHQ-4 score; life satisfaction (0–10).'));
C.push(p('Coding of hours. Category midpoints 0.5, 1, 2, 3, 4; "more than 4 hours" as 5; "no time savings" as 0; "required additional time" as −1. Frequency (daily = 1, less than daily = 2) enters the hours models as a control from row 2 of the ladder onward.'));

const doc = new Document({ creator: 'Workplace Social Science', title: 'The Gender Gap in AI at Work: HTOPS March 2026 Addendum',
  styles: { default: { document: { run: { font: FONT, size: 22 } } }, paragraphStyles: [
    { id: 'Heading1', name: 'Heading 1', basedOn: 'Normal', next: 'Normal', quickFormat: true, run: { size: 32, bold: true, font: FONT, color: '1F3B63' }, paragraph: { outlineLevel: 0 } },
    { id: 'Heading2', name: 'Heading 2', basedOn: 'Normal', next: 'Normal', quickFormat: true, run: { size: 26, bold: true, font: FONT, color: '2A78D6' }, paragraph: { outlineLevel: 1 } },
    { id: 'Heading3', name: 'Heading 3', basedOn: 'Normal', next: 'Normal', quickFormat: true, run: { size: 22, bold: true, font: FONT, color: '0B0B0B' }, paragraph: { outlineLevel: 2 } } ] },
  numbering: { config: [{ reference: 'num', levels: [{ level: 0, format: LevelFormat.DECIMAL, text: '%1.', alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 540, hanging: 360 } } } }] }] },
  sections: [{ properties: { page: { size: { width: 12240, height: 15840 }, margin: { top: 1300, bottom: 1200, left: 1440, right: 1440 } } },
    footers: { default: new Footer({ children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: 'Gender gap addendum: March 2026 HTOPS   |   Page ', font: FONT, size: 16, color: '52514E' }), new TextRun({ children: [PageNumber.CURRENT], font: FONT, size: 16, color: '52514E' })] })] }) },
    children: C }] });
Packer.toBuffer(doc).then(buf => { fs.writeFileSync('reports/AI_at_Work_Gender_Gap_Addendum.docx', buf); console.log('written'); });
